name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Specify the environment to use the secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.x"  # Latest Node.js 22.x version

      - name: Install dependencies
        run: |
          npm install

      - name: Build the application
        run: |
          npm run build

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.HOST }}  # EC2 instance DNS
          USER: ${{ secrets.USER }}
        run: |
          # Save SSH key to file
          echo "${{ secrets.SSH_SECRET_KEY }}" > key.pem
          chmod 600 key.pem

          # Rsync to the instance
          rsync -az --no-perms --no-times -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./lib ./package.json $USER@$HOST:/home/ubuntu/vital-signs

          # Connect to EC2 instance and ensure PM2 starts the app
          ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd /home/ubuntu/vital-signs
            # Check if the app is running, start if not
            if ! pm2 list | grep -q 'app'; then
              echo "Starting the app with PM2"
              pm2 start lib/main.js --name app  # Replace with your app's entry point
            else
              echo "App already running, restarting..."
              pm2 restart all
            fi
          EOF
